services:
  sensewatch:
    container_name: sensewatch
    image: sensewatch   # your locally built image
    privileged: true
    restart: unless-stopped
    shm_size: "256mb"
    ports:
      - "8971:8971"
      - "5050:5000"   # Web UI
      - "8554:8554"   # RTSP restreams (if enabled)
      - "1935:1935"   # RTMP restreams (if enabled)
    volumes:
      - ./config:/config   # your config.yml
      - ./media:/media        # optional: recordings/snapshots
      - type: tmpfs           # cache in memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - FRIGATE_RTSP_PASSWORD=testing123
